100/enhancement/create login screen in mobile app
millennicare/millennicare.com pull request #129
Opened 2024-06-28 00:58 UTC by DerickPineda

Login and Sign Up screen are both done. Followed the careseeker app as an example. Edited the spacing a little bit. 

Passes the lint and type check however for the lint check I ignored two require import statements for images. Tried to find a workaround however I don't know if React Native has a work around. Ignored that line for both pages for the meantime.

2024-06-28 05:26 UTC, stemca requested changes
looks good, just a few nitpicky things we can fix!

2024-06-28 05:26 UTC, stemca commented on apps/careseeker-mobile/src/app/auth/sign-in/index.tsx
> +  const { mutateAsync } = api.auth.login.useMutation();
You can disable the Button below with the isLoading prop to prevent multiple requests

2024-06-28 05:26 UTC, stemca commented on apps/careseeker-mobile/src/app/auth/sign-up/index.tsx
> +  const { mutateAsync } = api.auth.register.useMutation();
same comment as above

2024-06-28 05:26 UTC, stemca commented on apps/careseeker-mobile/src/lib/api/auth.tsx
file not needed, you can delete it

2024-07-11 03:21 UTC, DerickPineda reviewed
Added changes to disable sign in/sign up button while isPending is true. 

Deleted auth.tsx file

2024-07-11 04:07 UTC, stemca approved these changes
looks good!

2024-07-11 04:12 UTC, DerickPineda commented on apps/careseeker-mobile/app.config.ts
Used the wrong one, fixed

2024-07-11 04:14 UTC, merged